### ISSUE TITLE
Math operations on parameters

### ISSUE THREAD

**Issue by automata** [jonnor/imgflo#87] opened 2015-09-11 17:37 UTC
Sometimes simple math operations on parameters are required. An example is when someone wants to rotate an image around its center.

Two other options: (1) create specific components when such operations are needed, like rotate-on-center (via @jonnor), or (2) having components to perform math operations.

**Comment by jonnor** [comment] 2015-10-02 15:30
Duplicate of #58

**Closed by jonnor** 2015-10-02 15:30 UTC
